### ISSUE TITLE
Add `tmp` dir to the .npmignore.

### ISSUE THREAD

**Issue by stefanpenner** [Chun-Yang/ember-poetic-crud-mixins#1]
https://github.com/ember-cli/ember-cli/issues/4199

like: https://github.com/ember-cli/ember-cli/commit/6ac18227ea571988fa9d9950e9a1051fdd990c7c

**Comment by Chun-Yang** [comment]
Just fixed https://github.com/Chun-Yang/ember-poetic-crud-mixins/commit/6bda879f734489c7a1fd89ae02e3731646030dbc
